type: object
properties:
  seqid:
    type: string
  entitlement_id:
    type: string
    format: uuid
  resource_name:
    type: string
  resource_id:
    type: string
    format: uuid
  activeEntitlementCountForResource:
    type: string
  title:
    type: string
  defaultCoverage:
    type: array
    items:
      $ref: ./CoverageStatement.yaml
  coverage:
    type: array
    items:
      $ref: ./CoverageStatement.yaml
  customCoverage:
    type: boolean
  identifiers:
    type: array
    items:
      $ref: ./IdentifierOccurrence.yaml
  suppress:
    type: boolean
  type:
    type: string
  license:
    type: string
  licenseId:
    type: string
    format: uuid
  eventType:
    type: string
    enum: [ADD, UPDATE, REMOVE]
  url:
    type: string
    format: uri
  packageIds:
    type: array
    items:
      type: object
      properties:
        type:
          type: string
        value:
          type: string
  templatedUrls:
    type: array
    items:
      $ref: ./TemplatedUrl.yaml
