allOf:
  - oneOf:
      - $ref: ./PackageContentItem.yaml
      - $ref: ./Package.yaml
  - type: object
    properties:
      _object:
        oneOf:
          - $ref: ./TitleInstance.yaml
          - $ref: ./PlatformTitleInstance.yaml
          - $ref: ./PackageContentItem.yaml
          - $ref: ./Package.yaml
        discriminator:
          propertyName: class
          mapping:
            org.olf.kb.TitleInstance: ./TitleInstance.yaml
            org.olf.kb.PlatformTitleInstance: ./PlatformTitleInstance.yaml
            org.olf.kb.PackageContentItem: ./PackageContentItem.yaml
            org.olf.kb.Pkg: ./Package.yaml
