type: object
properties:
  id:
    type: string
    format: uuid
  class:
    type: string
  coverage:
    type: array
    items:
      $ref: ./CoverageStatement.yaml
  customCoverage:
    type: boolean
  dateCreated:
    type: string
    format: date-time
  lastUpdated:
    type: string
    format: date-time
  name:
    type: string
  normalizedName:
    type: string
    readOnly: true
  description:
    type: string
  publicationType:
    oneOf:
      - type: string
      - $ref: ./Refdata.yaml
  suppressFromDiscovery:
    type: boolean
  subType:
    oneOf:
      - type: string
      - $ref: ./Refdata.yaml
  tags:
    type: array
    items:
      $ref: ./Tag.yaml
  type:
    oneOf:
      - type: string
      - $ref: ./Refdata.yaml
  alternateResourceNames:
    type: array
    items: 
      $ref: ./AlternateResourceName.yaml
  identifiers:
    type: array
    items:
      $ref: ./IdentifierOccurrence.yaml
