type: object
properties:
  amendments:
    type: array
    items:
      $ref: ./LinkedAmendment.yaml
  id:
    type: string
  owner:
    type: string
    format: uuid
  remoteId:
    type: string
    format: uuid
  remoteId_object:
    type: object
  status:
    oneOf:
      - type: string
      - $ref: ../../common/schemas/Refdata.yaml
