type: object
properties:
  id:
    type: string
    format: uuid
  message:
    type: string
  dateCreated:
    type: integer
  origin:
    type: string
    format: uuid
  type:
    type: string
  additionalInfo:
    type: object
    properties:
      jobId:
        type: string
        format: uuid
      tenant:
        type: string
      tenantId:
        type: string
