type: object
required:
  - name
properties:
  id:
    type: string
    format: uuid
  name:
    type: string
  dateCreated:
    type: string
    format: date-time
  lastUpdated:
    type: string
    format: date-time
  locators:
    type: array
    items:
      type: object
      properties:
        domainName:
          type: string
        id:
          type: string
          format: uuid
