type: object
required:
  - platform
  - titleInstance
  - class
allOf:
  - $ref: ./ErmResource.yaml
  - properties:
      class:
        enum:
          - org.olf.kb.PlatformTitleInstance
      longName:
        type: string
      platform:
        $ref: ./Platform.yaml
      titleInstance:
        $ref: ./TitleInstance.yaml
      url:
        type: string
        format: uri
