parameters:
  - $ref: ../common/parameters/x-okapi-tenant.yaml
get:
  tags:
    - Files
  summary: Get a set of File records
  operationId: getFiles
  parameters:
    $ref: ../common/parameters/queryParameters.yaml
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            oneOf:
              - $ref: ../components/schemas/FileResults.yaml
              - $ref: ../components/schemas/FileResultsArray.yaml
    '400':
      description: Bad request error
    '403':
      description: Forbidden
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../common/schemas/GrailsErrorResponse.yaml
post:
  tags:
    - Files
  summary: Upload a file
  operationId: postFiles
  requestBody:
    required: true
    content:
      multipart/form-data:
        schema:
          type: object
          required:
            - upload
          properties:
            upload:
              type: string
              format: binary
  responses:
    '201':
      description: Created
      content:
        application/json:
          schema:
            $ref: ../components/schemas/File.yaml
    '400':
      description: Bad request error
    '403':
      description: Forbidden
    '422':
      description: Validation error
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ApplicationError.yaml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../common/schemas/GrailsErrorResponse.yaml
