parameters:
  - $ref: ../common/parameters/x-okapi-tenant.yaml
post:
  tags:
    - Jobs
  summary: Create and queue a comparison job
  operationId: postComparisonJob
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/CreateComparisonJobBody.yaml
    required: true
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ComparisonJob.yaml
    '400':
      description: Bad request error
    '403':
      description: Forbidden
    '422':
      description: Validation error
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ApplicationError.yaml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../common/schemas/GrailsErrorResponse.yaml
