parameters:
  - $ref: ../common/parameters/x-okapi-tenant.yaml
  - $ref: ../components/parameters/jobId.yaml
get:
  tags:
    - Jobs
  summary: Get the full (info and error) log for a specified job
  operationId: getJobFullLog
  parameters:
    $ref: ../common/parameters/queryParameters.yaml
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            oneOf:
              - $ref: ../components/schemas/LogEntryResults.yaml
              - $ref: ../components/schemas/LogEntryResultsArray.yaml
    '400':
      description: Bad request error
    '403':
      description: Forbidden
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../common/schemas/GrailsErrorResponse.yaml
