description: >-
  Supports search and creation of remote Knowledge Base records. A remote KB
  is a repository (e.g. a package/title resolver) that this module can
  harvest coverage, package, and title data from.
parameters:
  - $ref: ../common/parameters/x-okapi-tenant.yaml
get:
  tags:
    - Remote Knowledge Bases
  summary: Get a set of remote Knowledge Base records
  operationId: getKbs
  parameters:
    $ref: ../common/parameters/queryParameters.yaml
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            oneOf:
              - $ref: ../components/schemas/KbResults.yaml
              - $ref: ../components/schemas/KbResultsArray.yaml
    '400':
      description: Bad request error
    '403':
      description: Forbidden
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../common/schemas/GrailsErrorResponse.yaml
post:
  tags:
    - Remote Knowledge Bases
  summary: Create a remote Knowledge Base record
  operationId: postKb
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/Kb.yaml
    required: true
  responses:
    '201':
      description: Created
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Kb.yaml
    '400':
      description: Bad request error
    '403':
      description: Forbidden
    '422':
      description: Validation error
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ApplicationError.yaml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../common/schemas/GrailsErrorResponse.yaml
