parameters:
  - $ref: ../components/parameters/x-okapi-tenant.yaml
  - $ref: ../components/parameters/metadataId.yaml
get:
  tags:
  - Packages
  summary: Get a specified package ingress metadata record
  operationId: getPackageMetadata
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/PackageIngressMetadata.yaml
    '400':
      description: Bad request error
    '403':
      description: Forbidden
    '404':
      description: Not found error
      content:
        application/json:
          schema:
            $ref: ../components/schemas/HttpError.yaml
    '500':
      description: Internal server error
