parameters:
  - $ref: ../components/parameters/x-okapi-tenant.yaml
  - $ref: ../components/parameters/pciId.yaml
get:
  tags:
  - PCIs
  summary: Get a specified package content item record
  operationId: getPci
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/PackageContentItem.yaml
    '400':
      description: Bad request error
    '403':
      description: Forbidden
    '404':
      description: Not found error
      content:
        application/json:
          schema:
            $ref: ../components/schemas/HttpError.yaml
    '500':
      description: Internal server error
put:
  tags:
  - PCIs
  summary: Update a package content item record
  operationId: putPci
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/PackageContentItem.yaml
    required: true
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/PackageContentItem.yaml
    '400':
      description: Bad request error
    '404':
      description: Not found error
      content:
        application/json:
          schema:
            $ref: ../components/schemas/HttpError.yaml
    '500':
      description: Internal server error
