parameters:
  - $ref: ../components/parameters/x-okapi-tenant.yaml
  - $ref: ../components/parameters/platformId.yaml
get:
  tags:
  - Platforms
  summary: Get a specified platform record
  operationId: getPlatform
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Platform.yaml
    '400':
      description: Bad request error
    '403':
      description: Forbidden
    '404':
      description: Not found error
      content:
        application/json:
          schema:
            $ref: ../components/schemas/HttpError.yaml
    '500':
      description: Internal server error
put:
  tags:
  - Platforms
  summary: Update a platform record
  operationId: putPlatform
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/Platform.yaml
    required: true
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Platform.yaml
    '400':
      description: Bad request error
    '404':
      description: Not found error
      content:
        application/json:
          schema:
            $ref: ../components/schemas/HttpError.yaml
    '500':
      description: Internal server error
