description: Returns the list of entitlement options (ways of acquiring the specified resource) -- packages or package content items that this resource could be entitled through
parameters:
  - $ref: ../common/parameters/x-okapi-tenant.yaml
  - $ref: ../components/parameters/ermResourceId.yaml
get:
  tags:
    - Resources
  summary: Get entitlement options for a specified resource
  operationId: getResourceEntitlementOptions
  parameters:
    $ref: ../common/parameters/queryParameters.yaml
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            oneOf:
              - $ref: ../components/schemas/EntitlementOptionResults.yaml
              - $ref: ../components/schemas/EntitlementOptionResultsArray.yaml
    '400':
      description: Bad request error
    '403':
      description: Forbidden
    '500':
      description: Internal server error
