parameters:
  - $ref: ../common/parameters/x-okapi-tenant.yaml
  - $ref: ../components/parameters/stringTemplateId.yaml
get:
  tags:
    - String Templates
  summary: Get a specified string template
  operationId: getStringTemplate
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/StringTemplate.yaml
    '400':
      description: Bad request error
    '403':
      description: Forbidden
    '404':
      description: Not found error
      content:
        application/json:
          schema:
            $ref: ../common/schemas/HttpError.yaml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../common/schemas/GrailsErrorResponse.yaml
put:
  tags:
    - String Templates
  summary: Update a string template
  operationId: putStringTemplate
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/StringTemplate.yaml
    required: true
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/StringTemplate.yaml
    '400':
      description: Bad request error
    '403':
      description: Forbidden
    '404':
      description: Not found error
      content:
        application/json:
          schema:
            $ref: ../common/schemas/HttpError.yaml
    '422':
      description: Validation error
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ApplicationError.yaml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../common/schemas/GrailsErrorResponse.yaml
delete:
  tags:
    - String Templates
  summary: Delete a specified string template
  operationId: deleteStringTemplate
  responses:
    '204':
      description: No content
    '400':
      description: Bad request error
    '403':
      description: Forbidden
    '404':
      description: Not found error
      content:
        application/json:
          schema:
            $ref: ../common/schemas/HttpError.yaml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../common/schemas/GrailsErrorResponse.yaml
