description: Supports retrieval of title instances that are entitled via at least one active agreement
parameters:
  - $ref: ../components/parameters/x-okapi-tenant.yaml
get:
  tags:
    - Titles
  summary: Get a set of entitled title instance records
  operationId: getEntitledTitles
  parameters:
    $ref: ../components/parameters/queryParameters.yaml
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            oneOf:
              - $ref: ../components/schemas/TitleInstanceResults.yaml
              - $ref: ../components/schemas/TitleInstanceResultsArray.yaml
    '400':
      description: Bad request error
    '403':
      description: Forbidden
    '500':
      description: Internal server error
