parameters:
  - $ref: ../components/parameters/x-okapi-tenant.yaml
  - $ref: ../components/parameters/titleId.yaml
get:
  tags:
    - Titles
  summary: Get a specified title instance record
  operationId: getTitle
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/TitleInstance.yaml
    '400':
      description: Bad request error
    '403':
      description: Forbidden
    '404':
      description: Not found error
      content:
        application/json:
          schema:
            $ref: ../components/schemas/HttpError.yaml
    '500':
      description: Internal server error
put:
  tags:
    - Titles
  summary: Update a title instance record
  operationId: putTitle
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/TitleInstance.yaml
    required: true
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/TitleInstance.yaml
    '400':
      description: Bad request error
    '404':
      description: Not found error
      content:
        application/json:
          schema:
            $ref: ../components/schemas/HttpError.yaml
    '500':
      description: Internal server error
