name: Integration test module

on:
  push:

jobs:
  work-source-identifier-tirs-tests:
    uses: ./.github/workflows/run-int-tests.yml
    with:
      testPath: org.olf.TIRS.WorkSourceIdentifier.*
      outputDirectory: WorkSourceIdentifierTests
  id-first-tirs-tests:
    uses: ./.github/workflows/run-int-tests.yml
    with:
      testPath: org.olf.TIRS.IdFirstTIRS.*
      outputDirectory: IdFirstTests
      tirsEnvVar: IdFirst
  agreement-tests:
    uses: ./.github/workflows/run-int-tests.yml
    with:
      testPath: org.olf.Agreements.*
      outputDirectory: Agreements
  string-template-tests:
    uses: ./.github/workflows/run-int-tests.yml
    with:
      testPath: org.olf.StringTemplate.*
      outputDirectory: StringTemplate
  general-tests:
    uses: ./.github/workflows/run-int-tests.yml
    with:
      testPath: org.olf.General.*
      outputDirectory: General
  publish-test-results:
    needs: [work-source-identifier-tirs-tests, id-first-tirs-tests, agreement-tests, string-template-tests, general-tests]
    runs-on: ubuntu-latest
    steps:
      - name: 'setup directories to accept test results'
        run: |
          mkdir -p testLogs/WorkSourceIdentifierTests
          mkdir -p testLogs/IdFirstTests
          mkdir -p testLogs/Agreements
          mkdir -p testLogs/StringTemplate
          mkdir -p testLogs/General
      - name: 'download WorkSourceIdentifier test results'
        uses: actions/download-artifact@v4
        with:
          name: WorkSourceIdentifierTests
          path: testLogs/WorkSourceIdentifierTests
      - name: 'download IdFirst test results'
        uses: actions/download-artifact@v4
        with:
          name: IdFirstTests
          path: testLogs/IdFirstTests
      - name: 'download Agreements test results'
        uses: actions/download-artifact@v4
        with:
          name: Agreements
          path: testLogs/Agreements
      - name: 'download StringTemplate test results'
        uses: actions/download-artifact@v4
        with:
          name: StringTemplate
          path: testLogs/StringTemplate
      - name: 'download General test results'
        uses: actions/download-artifact@v4
        with:
          name: General
          path: testLogs/General
      - name: Display structure of downloaded files
        run: ls -R
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "testLogs/**/*.xml"
