name: Publish test results

on:
  workflow_run:
    workflows: ["Integration test module"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'donwload test results'
        uses: actions/download-artifact@v4
        with:
          name: testLogfiles
      - name: Display structure of downloaded files
        run: ls -R
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: "service/build/test-results/**/*.xml"